sudo: required
services: 
  - docker

before_install:
  - docker build -t annikenholst/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true annikenholst/react-test npm test

after_success:
  - docker build -t annikenholst/multi-client ./client
  - docker build -t annikenholst/multi-nginx ./nginx
  - docker build -t annikenholst/multi-server ./server
  - docker build -t annikenholst/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push annikenholst/multi-client
  - docker push annikenholst/multi-nginx
  - docker push annikenholst/multi-server
  - docker push annikenholst/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY